WITH BASE_MOVIMENTOS AS (
    SELECT
        M.CODPROD,
        M.CODFORNEC,
        M.CODFILIAL,
        PF.ENVIARFORCAVENDAS,
        ROW_NUMBER() OVER (
            PARTITION BY M.CODPROD
            ORDER BY M.DTMOV
        ) AS RN
    FROM
        PCMOV M
        JOIN PCPRODFILIAL PF
          ON PF.CODPROD = M.CODPROD
         AND PF.CODFILIAL = M.CODFILIAL
         AND PF.ENVIARFORCAVENDAS = 'S'
    WHERE
        M.DTMOV BETWEEN TO_DATE('01/04/2025', 'DD/MM/YYYY')
                      AND TO_DATE('30/06/2025', 'DD/MM/YYYY')
        AND M.NUMPED IS NOT NULL
        AND M.NUMPED <> 0
        AND M.CODFORNEC = 37
)
SELECT
    CODFILIAL,
    COUNT(DISTINCT CODPROD) AS QTDE_PRODUTOS
FROM
    BASE_MOVIMENTOS
WHERE
    RN = 1
GROUP BY
    CODFILIAL
ORDER BY
    CODFILIAL;
