SELECT DISTINCT
    E.CODPROD
FROM
    PCEST E
    JOIN PCPRODFILIAL PF
      ON PF.CODPROD = E.CODPROD
     AND PF.CODFILIAL = E.CODFILIAL
    JOIN PCPRODUT P
      ON P.CODPROD = E.CODPROD
WHERE
    P.CODFORNEC = 52
    AND PF.ENVIARFORCAVENDAS = 'S'
    AND E.QTEST > 0
ORDER BY
    E.CODPROD;
