SELECT
        COUNT(DISTINCT
        M.CODPROD) AS QTD_PROD,
        M.CODFORNEC,
        M.CODFILIAL
    FROM
        PCMOV M
        JOIN PCPRODFILIAL PF
          ON PF.CODPROD = M.CODPROD
         AND PF.CODFILIAL = M.CODFILIAL
         AND PF.ENVIARFORCAVENDAS = 'S'
    WHERE
        M.DTMOV BETWEEN TO_DATE('01/04/2025', 'DD/MM/YYYY')
                      AND TO_DATE('30/06/2025', 'DD/MM/YYYY')
        AND M.CODFORNEC = 52
GROUP BY M.CODFORNEC, M.CODFILIAL;